// Code generated by protoc-gen-go. DO NOT EDIT.
// source: healthsignal.proto

package healthsignal

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_healthsignal_2ed9404e15afd528, []int{0}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Ping struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	RequestDuration      int32    `protobuf:"varint,2,opt,name=requestDuration,proto3" json:"requestDuration,omitempty"`
	ConnectionDuration   int32    `protobuf:"varint,3,opt,name=connectionDuration,proto3" json:"connectionDuration,omitempty"`
	Location             string   `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	Endpoint             int32    `protobuf:"varint,5,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	TimedOut             bool     `protobuf:"varint,6,opt,name=timedOut,proto3" json:"timedOut,omitempty"`
	OnlineStatus         int32    `protobuf:"varint,7,opt,name=onlineStatus,proto3" json:"onlineStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_healthsignal_2ed9404e15afd528, []int{1}
}
func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (dst *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(dst, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

func (m *Ping) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Ping) GetRequestDuration() int32 {
	if m != nil {
		return m.RequestDuration
	}
	return 0
}

func (m *Ping) GetConnectionDuration() int32 {
	if m != nil {
		return m.ConnectionDuration
	}
	return 0
}

func (m *Ping) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *Ping) GetEndpoint() int32 {
	if m != nil {
		return m.Endpoint
	}
	return 0
}

func (m *Ping) GetTimedOut() bool {
	if m != nil {
		return m.TimedOut
	}
	return false
}

func (m *Ping) GetOnlineStatus() int32 {
	if m != nil {
		return m.OnlineStatus
	}
	return 0
}

func init() {
	proto.RegisterType((*Empty)(nil), "Empty")
	proto.RegisterType((*Ping)(nil), "Ping")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HealthSignalClient is the client API for HealthSignal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HealthSignalClient interface {
	SavePing(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Empty, error)
}

type healthSignalClient struct {
	cc *grpc.ClientConn
}

func NewHealthSignalClient(cc *grpc.ClientConn) HealthSignalClient {
	return &healthSignalClient{cc}
}

func (c *healthSignalClient) SavePing(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/HealthSignal/SavePing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HealthSignalServer is the server API for HealthSignal service.
type HealthSignalServer interface {
	SavePing(context.Context, *Ping) (*Empty, error)
}

func RegisterHealthSignalServer(s *grpc.Server, srv HealthSignalServer) {
	s.RegisterService(&_HealthSignal_serviceDesc, srv)
}

func _HealthSignal_SavePing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Ping)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthSignalServer).SavePing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/HealthSignal/SavePing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthSignalServer).SavePing(ctx, req.(*Ping))
	}
	return interceptor(ctx, in, info, handler)
}

var _HealthSignal_serviceDesc = grpc.ServiceDesc{
	ServiceName: "HealthSignal",
	HandlerType: (*HealthSignalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SavePing",
			Handler:    _HealthSignal_SavePing_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "healthsignal.proto",
}

func init() { proto.RegisterFile("healthsignal.proto", fileDescriptor_healthsignal_2ed9404e15afd528) }

var fileDescriptor_healthsignal_2ed9404e15afd528 = []byte{
	// 226 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x8d, 0x6e, 0xbb, 0x75, 0x58, 0x10, 0xe6, 0x20, 0x65, 0xbd, 0x94, 0x9e, 0x0a, 0x42,
	0x0f, 0xfa, 0x0a, 0x0a, 0xde, 0x94, 0xf6, 0x09, 0x62, 0x77, 0xd8, 0x0d, 0xb4, 0x93, 0xda, 0x4e,
	0x05, 0xdf, 0xda, 0x47, 0x90, 0x4c, 0x25, 0xa0, 0xec, 0x29, 0x7c, 0xff, 0xff, 0x27, 0x90, 0x0f,
	0xf0, 0x44, 0xb6, 0x97, 0xd3, 0xec, 0x8e, 0x6c, 0xfb, 0x7a, 0x9c, 0xbc, 0xf8, 0x72, 0x0b, 0xc9,
	0xf3, 0x30, 0xca, 0x57, 0xf9, 0x6d, 0x60, 0xf3, 0xe6, 0xf8, 0x88, 0xb7, 0x90, 0xce, 0x62, 0x65,
	0x99, 0x73, 0x53, 0x98, 0x2a, 0x69, 0x7e, 0x09, 0x2b, 0xb8, 0x99, 0xe8, 0x63, 0xa1, 0x59, 0x9e,
	0x96, 0xc9, 0x8a, 0xf3, 0x9c, 0x5f, 0xea, 0xe0, 0x7f, 0x8c, 0x35, 0x60, 0xe7, 0x99, 0xa9, 0x0b,
	0x14, 0xc7, 0x57, 0x3a, 0x3e, 0xd3, 0xe0, 0x1e, 0xb2, 0xde, 0x77, 0xeb, 0x6a, 0x53, 0x98, 0xea,
	0xba, 0x89, 0x1c, 0x3a, 0xe2, 0xc3, 0xe8, 0x1d, 0x4b, 0x9e, 0xe8, 0x0b, 0x91, 0x43, 0x27, 0x6e,
	0xa0, 0xc3, 0xeb, 0x22, 0x79, 0x5a, 0x98, 0x2a, 0x6b, 0x22, 0x63, 0x09, 0x3b, 0xcf, 0xbd, 0x63,
	0x6a, 0xd7, 0xbf, 0x6c, 0xf5, 0xee, 0x9f, 0xec, 0xe1, 0x1e, 0x76, 0x2f, 0x6a, 0xa4, 0x55, 0x23,
	0x78, 0x07, 0x59, 0x6b, 0x3f, 0x49, 0x2d, 0x24, 0x75, 0x38, 0xf6, 0x69, 0xbd, 0xda, 0xb9, 0x78,
	0x4f, 0xd5, 0xd7, 0xe3, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe3, 0x4c, 0xe8, 0xee, 0x45, 0x01,
	0x00, 0x00,
}
